---
- name: Prepare
  hosts: mock_server
  become: true
  tasks:
    - name: Start mock server
      raw: "nohup java -Dfile.encoding=UTF-8 -cp /mockserver-netty-jar-with-dependencies.jar:/libs/* -Dmockserver.propertyFile=/mockserver.properties org.mockserver.cli.Main -serverPort 1080 </dev/null >/dev/null 2>&1 & sleep 1"
      changed_when: false

- name: Set Expectations
  hosts: mock_server
  connection: local
  gather_facts: false
  tasks:
    - name: Reset mock server expectations
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/reset"
        method: PUT
        status_code: 200
        headers:
          Content-Type: application/json
        validate_certs: false

    - name: Create mock server expectations based on controller OpenAPI spec
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/openapi"
        method: PUT
        body:
          specUrlOrPayload: "{{ lookup('file','files/controller-3-9-openapi-spec.json') }}"
          operationsAndResponses:
            login: "204"
        status_code: 201
        body_format: json
        headers:
          Content-Type: application/json
        validate_certs: false
